CREATE DATABASE AIRLINES;
USE AIRLINES;

CREATE TABLE IF NOT EXISTS FLIGHTS 
(	fno  INTEGER,
	src  VARCHAR(20),
	dest  VARCHAR(20),
	distance  INTEGER,
	departs TIME,
	arrives TIME,
	price DOUBLE,
	PRIMARY KEY(fno)
);

CREATE TABLE IF NOT EXISTS AIRCRAFT
(	aid INTEGER,
    aname  VARCHAR(20),
    cruisingrange INTEGER,
	fno  INTEGER,
	PRIMARY KEY(aid),
	FOREIGN KEY(fno) REFERENCES FLIGHTS(fno)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(	eid INTEGER,
    ename  VARCHAR(20),
	salary INTEGER,
	PRIMARY KEY(eid)
);

CREATE TABLE IF NOT EXISTS CERTIFIED
(	eid INTEGER,
	aid INTEGER,
	PRIMARY KEY(eid,aid),
	FOREIGN KEY(eid) REFERENCES EMPLOYEE(eid),
	FOREIGN KEY(aid) REFERENCES AIRCRAFT(aid)
);

