
SELECT DISTINCT a.aname 
FROM AIRCRAFT a 
WHERE a.aid IN ( 
	SELECT DISTINCT c.aid 
	FROM CERTIFIED c 
	WHERE eid IN (
		SELECT DISTINCT eid 
		FROM EMPLOYEE 
		WHERE salary > 80000
	)
);


SELECT DISTINCT a.aname 
FROM AIRCRAFT a 
WHERE a.aid IN (
	SELECT c.aid 
	FROM CERTIFIED c, EMPLOYEE e 
	WHERE c.eid = e.eid AND NOT EXISTS(
		SELECT * 
		FROM EMPLOYEE e1 
		WHERE e1.eid = e.eid AND salary < 80000
	)
);

