CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE IF NOT EXISTS STUDENT(	
	snum  INTEGER,
	sname  VARCHAR(20),
	major  VARCHAR(20),
	slevel  VARCHAR(20),
	age  INTEGER,
	PRIMARY KEY(snum)
);

CREATE TABLE IF NOT EXISTS FACULTY(
	fid INTEGER,
    fname  VARCHAR(20),
	deptid INTEGER,
	PRIMARY KEY(fid)
);

CREATE TABLE IF NOT EXISTS CLASS(
    cname  VARCHAR(20),
    meets_at  VARCHAR(20),
    room  VARCHAR(20),
    fid INTEGER,
	PRIMARY KEY(cname),
	FOREIGN KEY(fid) REFERENCES FACULTY(fid)
);

CREATE TABLE IF NOT EXISTS ENROLLED(
	snum INTEGER,
    cname  VARCHAR(20),
	PRIMARY KEY(snum,cname),
	FOREIGN KEY(snum) REFERENCES STUDENT(snum),
	FOREIGN KEY(cname) REFERENCES CLASS(cname)
);

